-- An enumerable let-bound latent (`b`) used as the CONDITION of an `if` whose
-- ARMS draw fresh randomness. `toIREnumerate` compiles the whole conditional
-- forward and compares the generated value against the sample, which is exact
-- only when the conditional is deterministic given the enumerated latents;
-- the arms are not, so `requireDeterministicUnderEnum` refuses -- eagerly,
-- with an `error`, and with a message that additionally misdiagnoses the
-- program as unbounded self-recursion ("... else main"), which it is not.
--
-- The refusal is over-conservative rather than protective: the *condition*
-- IS deterministic given the enumerated latent, so each enumerated value of
-- `b` leaves an ordinary probability query over the selected arm. The proof
-- that the information is available is that hoisting the fresh draw into its
-- own enumerable binding answers correctly today:
--   main = draw b = Uniform < 0.5 in draw n = Uniform < 0.9 in
--            (b, if b then n else (not n))
--   -> p((True, True)) = 0.45   p((True, False)) = 0.05
--      p((False, True)) = 0.05  p((False, False)) = 0.45
-- which are also the idealized values for this program.
--
-- Found by the `exact-eig-question-asking` experiment, whose noisy-oracle
-- model is exactly this shape (a shared hidden latent, each observation a
-- fresh Bernoulli flip). See task enum-let-latent-gates-fresh-draw.
expect-failure: diagnostic "generate-backed fallback"
