-- Shrunk from a typed fuzz draw (prop_Fuzz_TypedCompileNeverCrashes),
-- verified against dev@4f5ef7e: a tuple/list projection under `Integrate`
-- (a Normal added to `fst` of a one-element list holding a one-element-list
-- tuple) falls through toIRInference's "found no way to convert to IR" case
-- and `error`s, since CompilerMonad has no failure channel to report a
-- program-level refusal on. The reviewer's own reduction: after unwrapping
-- the projections this "just looks like Normal + ConstantFloat, which
-- should compile" -- a small blind spot rather than a shape that should be
-- refused, per the review notes; still an open decision at time of writing,
-- so no numeric row is pinned, only the crash.
expect-failure: diagnostic "found no way to convert to IR"
